#!/bin/bash
# 
# Script to send a notification and sound when the previous command is finished. 
# 
# You can use another method to play the sound, use another notification sound or the popup method by using your own locations / commands. Also check that command paths are adapted to your system.
#
# This can be very handy when manipulating multiple shells at once during various operations such as file transfert, disk utilities, scans, enumeration & bruteforce tools...
#
# Requirements (in the current state): alsa-utils, libnotify.
# 
# Usage (only if the command is successful): [...] && ~/alert-script "TASK-NAME"
# Usage for both successful & unsuccessful command: [...] && alert-script "TASKE DONE" || alert-script "TASK FAILED" 
task="$1"
/usr/bin/notify-send "$1"
/usr/bin/aplay /usr/share/sounds/speech-dispatcher/test.wav


